'''
    File name: main.py
    Author: Andrew Robinson
    Date Created: 7/31/2019
    Last Modified: 8/18/2019
    Python Version 3.6
'''

from bot import Bot

import discord
from discord.ext import commands
from discord.utils import get

def main():
    
    #A token is generated by discordapp.com for each unique bot
    #This token is stored in a .txt file and read into a string to be passed into the bot
    tokenFile = open("token.txt", 'r')
    TOKEN = tokenFile.read().replace('\n', '')
    tokenFile.close()

    #Create the Botify object initialize with the token and chosen command prefix
    #In this case, commands will be prefixed with a forward slash. E.G: '/play' will run the play command
    botify = Bot(TOKEN, '/')

    botify.run()

#------------------------------------------------------------------------------

main()
